set nocp
set backspace=indent,eol,start
set nu
filetype on
syntax on
set ai
set smartindent
set tabstop=4
set shiftwidth=4
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
set fileencoding=utf-8
